#!/usr/bin/env bash
# Publish/refresh the StartOS community registry on the website for a seeder
# release: regenerate the /package/v0 metadata + bump the _redirects s9pk target
# to the release tag, then (opt-in) open + squash-merge a website PR. The website
# is a Cloudflare project that deploys on merge to main, so the merge is the
# deploy. Run AFTER the GitHub release + s9pk asset exist — the metadata
# advertises the version and _redirects points at that release's asset.
#
# Mirrors build-umbrel-image.sh's official-store flow: a fresh branch cut off
# origin/main, bump, and an opt-in push + gh PR (here we also merge it, since
# it's our own repo and the merge triggers the deploy).
#
# Usage: publish-start9-registry.sh [version]
#
# Env:
#   WEBSITE_DIR          (required) a clone of the website repo. For the auto-PR
#                        path use a DEDICATED clone: the branch is cut fresh off
#                        origin/main (git checkout -B), discarding leftovers.
#   WEBSITE_REGISTRY_PR  1 = commit, push the branch, open + squash-merge the PR
#                        via gh (deploys on merge). Default = regenerate the files
#                        + print the git/gh commands to run yourself.
#   S9PK                 built s9pk path
#                        (default seeder-launcher/start9/pearcircle-seeder.s9pk)
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
START9_DIR="$REPO_ROOT/seeder-launcher/start9"

# --- version ---------------------------------------------------------------
VERSION="${1:-}"
[ -z "$VERSION" ] && VERSION="$( (git -C "$REPO_ROOT" describe --tags --abbrev=0 2>/dev/null || true) | sed 's/^v//' )"
[ -z "$VERSION" ] && VERSION="$(node -p "require('$REPO_ROOT/seeder-launcher/package.json').version" 2>/dev/null || echo 0.0.0)"
VERSION="${VERSION#v}"

: "${WEBSITE_DIR:?set WEBSITE_DIR to a clone of the website repo}"
[ -d "$WEBSITE_DIR/.git" ] || { echo "publish-start9-registry: $WEBSITE_DIR is not a git clone" >&2; exit 1; }
S9PK="${S9PK:-$START9_DIR/pearcircle-seeder.s9pk}"
[ -f "$S9PK" ] || { echo "publish-start9-registry: s9pk not found: $S9PK (run build-start9-s9pk.sh first)" >&2; exit 1; }

AUTO="${WEBSITE_REGISTRY_PR:-}"
BRANCH="start9-registry-v${VERSION}"
echo "==> Publishing StartOS registry for seeder v$VERSION (website $WEBSITE_DIR)"

# For the automated path, cut a fresh branch off the latest main so the diff is
# only the registry (and a lingering same-version branch from a re-run resets).
base="main"
if [ "$AUTO" = 1 ]; then
  git -C "$WEBSITE_DIR" fetch -q origin
  base="$(git -C "$WEBSITE_DIR" remote show origin 2>/dev/null | sed -n 's/.*HEAD branch: //p')"; base="${base:-main}"
  git -C "$WEBSITE_DIR" checkout -q -B "$BRANCH" "origin/${base}"
fi

# Regenerate the metadata + bump the _redirects s9pk target into the working tree.
echo "==> regenerating /package/v0 metadata + _redirects for v$VERSION ..."
OUT_DIR="$WEBSITE_DIR" SKIP_S9PK=1 bash "$START9_DIR/registry/build-registry.sh" "$S9PK"
if [ -f "$WEBSITE_DIR/_redirects" ]; then
  sed -i -E "s#(releases/download/)v[0-9.]+(/pearcircle-seeder\.s9pk)#\1v${VERSION}\2#" "$WEBSITE_DIR/_redirects"
fi

# Nothing to publish? (re-run at the same version — metadata is deterministic.)
if [ -z "$(git -C "$WEBSITE_DIR" status --porcelain -- package _redirects)" ]; then
  echo "==> registry already current for v$VERSION — nothing to publish."
  exit 0
fi

if [ "$AUTO" = 1 ]; then
  ( cd "$WEBSITE_DIR"
    git add package _redirects
    git commit -q -m "chore: StartOS registry -> seeder v${VERSION}"
    git push -q -f -u origin "$BRANCH"
    if [ -z "$(gh pr list --head "$BRANCH" --state open --json number --jq '.[0].number' 2>/dev/null)" ]; then
      gh pr create --base "$base" --head "$BRANCH" \
        --title "chore: StartOS registry -> seeder v${VERSION}" \
        --body "Regenerated \`/package/v0\` metadata + \`_redirects\` for seeder v${VERSION}. Auto-generated by publish-start9-registry.sh; merging deploys the registry (Cloudflare)." \
        >/dev/null
    fi
    if gh pr merge "$BRANCH" --squash --delete-branch >/dev/null 2>&1; then
      echo "==> Website registry deployed — PR merged to $base (Cloudflare deploys on merge)."
    else
      echo "    WARNING: PR opened for v$VERSION but auto-merge failed — merge it manually to deploy." >&2
    fi
  )
else
  echo ""
  echo "==> Registry files regenerated in $WEBSITE_DIR (not committed). To publish:"
  echo "      cd $WEBSITE_DIR"
  echo "      git checkout -B $BRANCH && git add package _redirects"
  echo "      git commit -m 'chore: StartOS registry -> seeder v${VERSION}'"
  echo "      git push -u origin $BRANCH"
  echo "      gh pr create --base $base --fill && gh pr merge --squash --delete-branch"
  echo "    (or set WEBSITE_REGISTRY_PR=1 to do all of that automatically)"
fi
