#!/usr/bin/env bash
# Publish/refresh the StartOS community registry on the website for a PearCircle
# seeder release: UPSERT the pearcircle-seeder metadata under /package/v0 (merging
# into the shared registry that also lists pearcal-seeder - never wiping it)
# and ensure the _redirects rule points its s9pk at the release tag, then
# (opt-in) open + squash-merge a website PR. The website is a Cloudflare project
# that deploys on merge to main, so the merge is the deploy. Run AFTER the GitHub
# release + s9pk asset exist - the metadata advertises the version and _redirects
# points at that release's asset.
#
# TWO registries are published, because StartOS changed protocol:
#   0.3.5.x  the static /package/v0 tree (build-registry.sh)
#   0.4.0+   a single JSON-RPC payload at /registry/0.4/index.json, served by
#            the website Worker at POST /rpc/v0 (build-registry-04.js)
# A 0.4 box reads NOTHING from the 0.3.5 tree, so skipping the second one makes
# the package invisible to every 0.4 user while looking fine on 0.3.5. Both
# generators upsert, since the registry is shared with the other PeerLoom seeders.
#
# Usage: publish-start9-registry.sh [version]
#
# Env:
#   WEBSITE_DIR          (required) a clone of the website repo. For the auto-PR
#                        path use a DEDICATED clone: the branch is cut fresh off
#                        origin/main (git checkout -B), discarding leftovers.
#   WEBSITE_REGISTRY_PR  1 = commit, push the branch, open + squash-merge the PR
#                        via gh (deploys on merge). Default = regenerate the files
#                        + print the git/gh commands to run yourself.
#   S9PK                 built s9pk path
#                        (default seeder-launcher/start9/pearcircle-seeder.s9pk)
#   S9PK_V2              built v2 s9pk for the 0.4 registry
#                        (default seeder-launcher/start9/pearcircle-seeder-v2.s9pk)
#   START_CLI_V2         0.4.x-era start-cli, needed to inspect the v2 s9pk
#                        (default: found on PATH)
#   RELEASE_REPO         GitHub owner/repo hosting the s9pk release asset
#                        (default peerloomllc/pearcircle)
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
START9_DIR="$REPO_ROOT/seeder-launcher/start9"
RELEASE_REPO="${RELEASE_REPO:-peerloomllc/pearcircle}"
# Registry paths touched by this script. Used for the leftover-clearing sweep,
# the has-anything-changed check and `git add`, so a new output path only has to
# be named once.
REG_PATHS=(package registry _redirects)

# --- version ---------------------------------------------------------------
VERSION="${1:-}"
[ -z "$VERSION" ] && VERSION="$( (git -C "$REPO_ROOT" describe --tags --abbrev=0 2>/dev/null || true) | sed 's/^v//' )"
[ -z "$VERSION" ] && VERSION="$(node -p "require('$REPO_ROOT/seeder-launcher/package.json').version" 2>/dev/null || echo 0.0.0)"
VERSION="${VERSION#v}"

: "${WEBSITE_DIR:?set WEBSITE_DIR to a clone of the website repo}"
[ -d "$WEBSITE_DIR/.git" ] || { echo "publish-start9-registry: $WEBSITE_DIR is not a git clone" >&2; exit 1; }
S9PK="${S9PK:-$START9_DIR/pearcircle-seeder.s9pk}"
[ -f "$S9PK" ] || { echo "publish-start9-registry: s9pk not found: $S9PK (run build-start9-s9pk.sh first)" >&2; exit 1; }
S9PK_V2="${S9PK_V2:-$START9_DIR/pearcircle-seeder-v2.s9pk}"

# The 0.4 payload is generated by inspecting the v2 s9pk, which needs the
# 0.4-era start-cli. Resolve it the same way build-start9-s9pk.sh does: the
# 0.3.5 SDK prints "StartOS CLI 0.3.5.1" and the new one "start-cli 1.1.0".
_v2_cli=""
for _cand in "${START_CLI_V2:-}" start-cli-1.1.0 start-cli; do
  [ -n "$_cand" ] || continue
  command -v "$_cand" >/dev/null 2>&1 || continue
  if "$_cand" --version 2>/dev/null | grep -qE '^start-cli [1-9]'; then _v2_cli="$_cand"; break; fi
done

AUTO="${WEBSITE_REGISTRY_PR:-}"
BRANCH="start9-registry-pearcircle-v${VERSION}"
echo "==> Publishing StartOS registry for pearcircle-seeder v$VERSION (website $WEBSITE_DIR)"

# For the automated path, cut a fresh branch off the latest main so the diff is
# only the registry (and a lingering same-version branch from a re-run resets).
base="main"
if [ "$AUTO" = 1 ]; then
  git -C "$WEBSITE_DIR" fetch -q origin
  base="$(git -C "$WEBSITE_DIR" remote show origin 2>/dev/null | sed -n 's/.*HEAD branch: //p')"; base="${base:-main}"
  # An earlier aborted run leaves its generated output in exactly the paths this
  # script rewrites, and `checkout -B` then refuses to switch over them:
  #   error: Your local changes to the following files would be overwritten by
  #   checkout: _redirects, package/v0/index, package/v0/latest
  # Worse, that leftover is generated against whatever main was at the time, so
  # keeping it would make the upsert below merge onto a stale base and could
  # revert a previous publish. It is pure generated output and is regenerated a
  # few lines down, so clear it. Scoped to the registry paths ONLY, so unrelated
  # edits elsewhere in the clone (CLAUDE.md, site content) are never touched.
  if [ -n "$(git -C "$WEBSITE_DIR" status --porcelain -- "${REG_PATHS[@]}")" ]; then
    echo "    clearing leftover registry output from a previous run (${REG_PATHS[*]})"
    git -C "$WEBSITE_DIR" checkout -q -- "${REG_PATHS[@]}" 2>/dev/null || true
    git -C "$WEBSITE_DIR" clean -qfd -- package registry 2>/dev/null || true
  fi
  git -C "$WEBSITE_DIR" checkout -q -B "$BRANCH" "origin/${base}"
else
  # Manual path: no branch is cut, so the upsert merges into whatever this clone
  # currently holds. A clone behind origin silently produces a stale-base merge
  # that drops entries added upstream since, so say so rather than fail quietly.
  git -C "$WEBSITE_DIR" fetch -q origin 2>/dev/null || true
  _behind="$(git -C "$WEBSITE_DIR" rev-list --count HEAD..origin/main 2>/dev/null || echo 0)"
  if [ "${_behind:-0}" -gt 0 ]; then
    echo "    WARNING: $WEBSITE_DIR is $_behind commit(s) behind origin/main." >&2
    echo "             The upsert merges into this tree, so a stale base can revert a" >&2
    echo "             previous publish. Run: git -C \"$WEBSITE_DIR\" pull --ff-only origin main" >&2
  fi
fi

# Merge the pearcircle-seeder metadata into the (possibly multi-package) tree.
echo "==> upserting pearcircle-seeder /package/v0 metadata for v$VERSION ..."
OUT_DIR="$WEBSITE_DIR" SKIP_S9PK=1 bash "$START9_DIR/registry/build-registry.sh" "$S9PK"

# Ensure the _redirects rules send /package/v0/pearcircle-seeder.s9pk (and the
# double-slash variant StartOS sometimes builds) at the release asset. Bump the
# tag in place if the rules exist, else append them.
RED="$WEBSITE_DIR/_redirects"
ASSET_BASE="https://github.com/${RELEASE_REPO}/releases/download"
touch "$RED"
if grep -qE '^//?package/v0/pearcircle-seeder\.s9pk' "$RED"; then
  sed -i -E "s#(${RELEASE_REPO}/releases/download/)v[0-9.]+(/pearcircle-seeder\.s9pk)#\1v${VERSION}\2#g" "$RED"
  echo "    bumped existing _redirects rules to v$VERSION"
else
  {
    echo "/package/v0/pearcircle-seeder.s9pk  ${ASSET_BASE}/v${VERSION}/pearcircle-seeder.s9pk  302"
    echo "//package/v0/pearcircle-seeder.s9pk  ${ASSET_BASE}/v${VERSION}/pearcircle-seeder.s9pk  302"
  } >> "$RED"
  echo "    appended _redirects rules for pearcircle-seeder v$VERSION"
fi

# --- the 0.4 registry ------------------------------------------------------
# 0.4 boxes read none of the above. They POST to /rpc/v0, which the website
# Worker answers from this one generated payload.
if [ ! -f "$S9PK_V2" ] || [ -z "$_v2_cli" ]; then
  echo ""
  echo "  !! SKIPPING the 0.4 registry entry - StartOS 0.4 users will not see" >&2
  echo "  !! pearcircle-seeder at all (0.3.5.x boxes are unaffected)." >&2
  if [ ! -f "$S9PK_V2" ]; then
    echo "  !!   missing: the v2 s9pk at $S9PK_V2 (build-start9-s9pk.sh emits it)" >&2
  fi
  if [ -z "$_v2_cli" ]; then
    echo "  !!   missing: a 0.4.x start-cli (set START_CLI_V2, or install start-cli 1.x)" >&2
  fi
  echo ""
else
  echo "==> upserting pearcircle-seeder into the 0.4 registry payload for v$VERSION ..."
  mkdir -p "$WEBSITE_DIR/registry/0.4"
  # 0.4 must download the V2 package: the published commitment is computed over
  # it, so handing a 0.4 box the v1 file yields a hash it cannot match and the
  # install fails. Hence its own /package/v1 path, leaving /package/v0 to serve
  # 0.3.5 boxes the v1 file they can actually read.
  if grep -qE '^//?package/v1/pearcircle-seeder\.s9pk' "$RED"; then
    sed -i -E "s#(${RELEASE_REPO}/releases/download/)v[0-9.]+(/pearcircle-seeder-v2\.s9pk)#\1v${VERSION}\2#g" "$RED"
    echo "    bumped existing /package/v1 _redirects rules to v$VERSION"
  else
    {
      echo "/package/v1/pearcircle-seeder.s9pk  ${ASSET_BASE}/v${VERSION}/pearcircle-seeder-v2.s9pk  302"
      echo "//package/v1/pearcircle-seeder.s9pk  ${ASSET_BASE}/v${VERSION}/pearcircle-seeder-v2.s9pk  302"
    } >> "$RED"
    echo "    appended /package/v1 _redirects rules for pearcircle-seeder v$VERSION"
  fi
  START_CLI="$_v2_cli" node "$START9_DIR/registry/build-registry-04.js" "$S9PK_V2" \
    --url "https://peerloomllc.com/package/v1/pearcircle-seeder.s9pk" \
    --icon "$START9_DIR/icon.png" \
    --out "$WEBSITE_DIR/registry/0.4/index.json"
fi

# Nothing to publish? (re-run at the same version - metadata is deterministic.)
if [ -z "$(git -C "$WEBSITE_DIR" status --porcelain -- "${REG_PATHS[@]}")" ]; then
  echo "==> registry already current for pearcircle-seeder v$VERSION - nothing to publish."
  exit 0
fi

if [ "$AUTO" = 1 ]; then
  ( cd "$WEBSITE_DIR"
    git add "${REG_PATHS[@]}"
    git commit -q -m "chore: StartOS registry -> pearcircle-seeder v${VERSION}"
    git push -q -f -u origin "$BRANCH"
    if [ -z "$(gh pr list --head "$BRANCH" --state open --json number --jq '.[0].number' 2>/dev/null)" ]; then
      gh pr create --base "$base" --head "$BRANCH" \
        --title "chore: StartOS registry -> pearcircle-seeder v${VERSION}" \
        --body "Upserted the \`/package/v0\` (StartOS 0.3.5.x) metadata and the \`/registry/0.4/index.json\` (StartOS 0.4+) payload, plus \`_redirects\`, for pearcircle-seeder v${VERSION} - merged alongside the other listed packages. Auto-generated by publish-start9-registry.sh; merging deploys the registry (Cloudflare)." \
        >/dev/null
    fi
    if gh pr merge "$BRANCH" --squash --delete-branch >/dev/null 2>&1; then
      echo "==> Website registry deployed - PR merged to $base (Cloudflare deploys on merge)."
    else
      echo "    WARNING: PR opened for v$VERSION but auto-merge failed - merge it manually to deploy." >&2
    fi
  )
else
  echo ""
  echo "==> Registry files regenerated in $WEBSITE_DIR (not committed). To publish:"
  echo "      cd $WEBSITE_DIR"
  echo "      git checkout -B $BRANCH && git add ${REG_PATHS[*]}"
  echo "      git commit -m 'chore: StartOS registry -> pearcircle-seeder v${VERSION}'"
  echo "      git push -u origin $BRANCH"
  echo "      gh pr create --base $base --fill && gh pr merge --squash --delete-branch"
  echo "    (or set WEBSITE_REGISTRY_PR=1 to do all of that automatically)"
fi
